### ISSUE TITLE
Track amount of data downloaded from S3

### ISSUE THREAD

**Issue by sciurus** [mozilla-services/tecken#1010]
Let's add a datadog metric to track the amount of data tecken downloads from S3.

This can be a counter that is incremented by the size of the object each time one is downloaded. See the [upload_file example](https://docs.datadoghq.com/developers/dogstatsd/data_types/).

**Comment by peterbe** [comment]
"incremented"? You mean a gauge, don't you?

**Comment by sciurus** [comment]
No, I mean a counter like is demonstrated in the example I linked. The problem with a gauge is that when the datadog agent receives the value, it overwrites the previous value. Let's say over the datadog agent's ten second flush inverval for statsd metrics you downloaded three objects from S3 that were 100kb, 200kb and 300kb. If you use a gauge, datadog agent will send the value 300kb to datadog.com. If you use a counter, the datadog agent will send the value 600kb to datadog.com

**Comment by peterbe** [comment]
Right. Got it.

**Comment by sciurus** [comment]
Should we have the symboldownloader_download_bytes metric in dev yet? I don't see anything in datadog.

**Comment by peterbe** [comment]
Dev doesn't get any traffic. That's maybe why it never hits that code point. I'll push some symbolication traffic to Stage.

**Comment by peterbe** [comment]
Try now.

**Comment by sciurus** [comment]
Woohoo, it's there!

FYI if you have a cheat sheet or script(s) for testing common symbols operations I'd be happy to poke at this sort of thing myself in the future.

**Comment by peterbe** [comment]
There are some scripts in https://github.com/mozilla-services/tecken-loadtests which are powerful but rather poorly maintained. It's basically me storing my scripts-during-development in a remote git repo. 

But, to test symbolication you can go to https://symbols.mozilla.org/symbolication and use the web UI thing for testing it. A nice thing is that it helps to remember what the HTTP curl structure is supposed to be. To try it you need a symbol and a hex. You can get them from https://symbols.mozilla.org/uploads but that requires that you're superuser. Or you can do the whole thing on stage and then you can upload your own symbols.

**Comment by peterbe** [comment]
This should be in prod now. Where did you add the new metrics in Datadog? The Tecken Performance dashboard?

**Comment by peterbe** [comment]
I've added it to the Tecken Performance dashboard now.
https://app.datadoghq.com/dash/339351/tecken-performance?live=true&page=0&is_auto=false&from_ts=1535394969754&to_ts=1535398569754&tile_size=l&fullscreen=350302918

**Comment by sciurus** [comment]
Looks good in prod, thanks again!

I've created https://app.datadoghq.com/dash/899121/bpittss-timeboard-27-aug-2018-1555?live=true&page=0&is_auto=false&from_ts=1535400477246&to_ts=1535404077246&tile_size=m
