### ISSUE TITLE
.pyup.yml syntax

### ISSUE THREAD

**Issue by Jwomers** [mozilla-services/tecken#1044]
Hi! After a bit of digging, it turns out the issue with the PyUp parsing of .pyup.yml is because the attributes of each requirement file need to be double tabbed or space here: https://github.com/mozilla-services/tecken/blob/fc634ee014f7f75fd18acfc99af1d17ebb840f6d/.pyup.yml#L7

You have:
```
  ...
  - docs-requirements.txt:
    pin: False
```

And you need:
```
  ...
  - docs-requirements.txt:
      pin: False
```

For correct parsing by PyUp.

**Comment by peterbe** [comment]
Ah! Smart sleuthing. I don't know why it was working before but maybe I broke it in [this commit](https://github.com/mozilla-services/tecken/commit/afd3480a65bec2ab770ffe4212af5571e4677b03#diff-50f285e3023eb0b37f3dc8671b7dace9) and didn't notice that the PRs stopped coming in.
