### ISSUE TITLE
gcs for local dev environment

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/tecken#1247]
If you, today, want to simulate GCS locally you can't. You have to actually have a real GCS bucket and real credentials.

With minio in docker-compose we were able to fake all that bucket and object put/get locally. Let's see if we can do the same for GCS.

**Comment by willkg** [comment]
Telemetry Edge has this (for pubsub): https://github.com/mozilla/gcp-ingestion/blob/master/ingestion-edge/pubsub_emulator.py

Maybe we can do something like that for GCS. We have this problem with Tecken and Socorro, so maybe that's worth spending a week of time on.

**Comment by willkg** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1552950
