### ISSUE TITLE
Fine-tuned timeout in GCS reads and puts

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/tecken#1248]
We S3, we are able to [finely control various timeouts](https://github.com/mozilla-services/tecken/blob/cf8de74de1c95188bb4badc4bd22d37278022bc6/tecken/settings.py#L47-L57). In particular, different timeouts depending on what the context is. That way we can be a lot more patient with uploads and very impatient with downloads. Also, I don't know what the default timeouts are in boto3 but we also don't want to exceed the gunicorn timeout (300s I think) when something's really busted but would rather just exit and error and have the client retry.

**Comment by peterbe** [comment]
This is going to be hard. Perhaps it can wait. The timeout can't be controlled on a per-request basis. See https://github.com/googleapis/google-cloud-python/issues/2988#issuecomment-278490149

**Comment by willkg** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1552951
