### ISSUE TITLE
Uploads pagination is potentially slow

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/tecken#1519]
The pagination of uploads is currently done the naive way of using batch size and pages. [Here](https://github.com/mozilla-services/tecken/blob/a89791f9e5ac73c1ed1188d8c6a588769d756a7d/tecken/api/views.py#L392-L394) and [here](https://github.com/mozilla-services/tecken/blob/a89791f9e5ac73c1ed1188d8c6a588769d756a7d/tecken/api/views.py#L448).

The pagination would a lot efficient if we know the last row of the page. Then we could do...

```python
for thing in queryset.filter(key__lt=previous_key_value)[:batch_size]:
    ...
```

instead of

```python
for thing in queryset.filter(key__lt=previous_key_value)[start:end]:
    ...
```

**Comment by willkg** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1552948
