### ISSUE TITLE
Do symbolication as a gzip stream

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/tecken#1663]
When adding support for GCS, it seems we (technically; me), lost the ability to read from a *stream* when doing the symbolication. 

See the lines: https://github.com/mozilla-services/tecken/blob/91927db02ea29446c8cf36f0139ef639125769eb/tecken/base/symboldownloader.py#L304-L307

It means that it will download all 100MB `xul.pbd/HEXHEXHEX/xul.sym` (which despite its file extension is actually gzipped) over the wire, un-gzip it internally/automatically to a ~400MB buffer and once all of that is loaded into memory the whole fat string is split by newlines an yielded [back](https://github.com/mozilla-services/tecken/blob/bc17c36e10a39c62144eb15e1d7ea0abb9f62530/tecken/symbolicate/views.py#L683-L703) to the consumer.

This is definitely a lot of memory to hold on to which could break the Gunicorn worker by OOM the process. It's roughly ~ 400MB + 70MB but could be a lot more if the symbolication mentions other of these massive libxul symbol files. 

It might be a non-issue on our beefy GCP web heads but it's definitely something A) we need to fully test before switching to GCP, and B) something that might be a performance problem. 

Thing is, when parsing a ~400MB string line by line, it might be something you want to start with ASAP *whilst you're waiting for the rest of the download* to complete. 
Also, if the whole massive download is held in memory it might make it a LOT easier to send it into a compiled program that does the parsing. E.g. a rust-python binary that takes in a unicode string and returns a dictionary.

**Comment by peterbe** [comment]
Also, a place to gain a quick win might be to attack this:
https://github.com/mozilla-services/tecken/blob/91927db02ea29446c8cf36f0139ef639125769eb/tecken/base/symboldownloader.py#L306-L307

It makes a whole massive string, then generates a new list, of the whole string, split by newlines. Since strings are immutable, won't that mean the ~400MB string adds another ~400MB to the heap?

In other words, we need to change those lines to use `iter_lines` which will read `CHUNK_SIZE` at a time and look for newline characters and yield back individual blocks. 

By the way, another option, if you have the whole string is to execute a multiprocessing pool in Python. You could do something like this:

```python
total_size = total_size_of_uncompressed_symbol_buffer_or_estimate
parsed = {}
mp_buffer = multiprocessing.Array(buffer)
# Pseudo multiprocessing pool code
with multipprocessing.Pool() as pool:
    for i in range(total_size // 1024 + 1):
        pool.start(parser, parsed, mp_buffer, i * 1024, (i + 1) * 1024)
    for task in pool:
        task.join()
```

**Comment by sciurus** [comment]
If nothing else, can't you download to an actual file on disk and then start to process it?

**Comment by peterbe** [comment]
Disk-as-buffer, yeah, it might work in terms of avoiding memory bloat but without thinking too deeply about it I theorize it's going to be too slow.

**Comment by sciurus** [comment]
It's not as elegant, but if getting streaming reads from the GCS object isn't feasible I think it's worth trying. Disks can be [pretty fast](https://cloud.google.com/compute/docs/disks/performance) and of course the kernel will keep file contents in memory when it can.

**Comment by peterbe** [comment]
For what it's worth; disk-as-buffer is how the Symbol Upload works. 
Independent of how the .zip file comes in (multipart form file or as URL), it gets unzip on disk. Then, once unzipped a concurrent worker deals with each file within the extracted directory.
