### ISSUE TITLE
the benchmarking documentation is truncated

### ISSUE THREAD

**Issue by froydnj** [mozilla-services/tecken#1695]
See [docs/benchmarking.rst](https://github.com/mozilla-services/tecken/blob/master/docs/benchmarking.rst), which just ends with "But basically the idea is that every benchmark is started by querying a".

**Comment by willkg** [comment]
I'm pretty sure that finishes the paragraph good enough. I'm also pretty sure benchmarking is a developers-only kind of feature and only available in a local dev environment, so I think this is good enough.

Thank you for pointing it out!
