### ISSUE TITLE
TimeoutError in Redis from get_symbol_offsets() 

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/tecken#1709]
https://sentry.prod.mozaws.net/operations/symbols-prod/issues/5418524/

```
ConnectionInterrupted: Redis TimeoutError: Timeout reading from socket
  File "django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "django_redis/cache.py", line 108, in get_many
    return self.client.get_many(*args, **kwargs)
  File "django_redis/client/default.py", line 353, in get_many
    raise ConnectionInterrupted(connection=client, parent=e)

TimeoutError: Timeout reading from socket
(16 additional frame(s) were not displayed)
...
  File "tecken/symbolicate/views.py", line 794, in inner
    return view_function(request, json_body)
  File "tecken/symbolicate/views.py", line 986, in symbolicate_v5_json
    result = symbolicator.symbolicate(job["stacks"], job["memoryMap"])
  File "tecken/symbolicate/views.py", line 172, in symbolicate
    informations = self.get_symbol_offsets(needed_modules_lookups)
  File "tecken/symbolicate/views.py", line 471, in get_symbol_offsets
    all_keys = store.get_many(cache_keys_keys)

TimeoutError: Timeout reading from socket
```

**Comment by peterbe** [comment]
Symbolication works (very) rougly like this:

1. What were the symbolicated stacks for module1 @ address1, module1 @ address2, module2 @ addressN, etc. ?
2. Tecken, in the form of calling `get_symbol_offsets()` figures out an `MGET` Redis query to get all the possible information it needs. 
3. Based on now knowing what's in the Redis Store cache, it can split up the list of modules into two lists: 1) the ones we already have in the Redis Store and 2) the ones we need to download from the internet (S3/GCS). 

If that Redis query times out, it's a shame, but it shouldn't break the symbolication! It just means we're going to have to forfeit the benefit the Redis Store cache. Having to re-download it from S3/GCS isn't horrible.

**Comment by peterbe** [comment]
What needs to be done is wrap the `get_symbol_offsets()` call such that it captures possible Redis `TimeoutError` errors and, apart from doing some logging or markus metrics incrementing, just proceeds as if the data wasn't there in Redis.

**Comment by willkg** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1552944
