### ISSUE TITLE
UPLOAD_INBOX_DIRECTORY is dead

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/tecken#1727]
Aka. `DJANGO_UPLOAD_INBOX_DIRECTORY`. 
In an early version of Tecken, the idea was to accept the uploaded .zip file ASAP and then say "200 OK We're working on it. Bye!". 
Then a Celery task would look into this inbox and start dealing with it. 

This was rewritten to not use Celery at all. The reason, I *think*, is that the Celery workers might be in a different container/web head so the file system is different. 

All mentions of it in code and documentation can be deleted. [E.g. this](https://github.com/mozilla-services/tecken/blob/42a59ba8282210cfc1d3913fd391b3c67768081c/tecken/settings.py#L487-L492)

**Comment by willkg** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1552915
