### ISSUE TITLE
version

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/tecken#260]
not sure if the problem is in the code of the service itself, or a deployment issue. But in the /\_\_version\_\_ endpoint on stage, the version field is an empty string

cc @pdehaan

**Comment by milescrabill** [comment]
I believe this is because the most recent deployment of symbols was deployed off of a CircleCI build number and not off of a git tag. Deployments off of tags shouldn't have this issue.

**Comment by peterbe** [comment]
Empty as expected: https://symbols.dev.mozaws.net/__version__
By tag: https://symbols.stage.mozaws.net/__version__
By tag: https://symbols.mozilla.org/__version__

Thanks for noticing!
