### ISSUE TITLE
Support symbol file format change in upstream Breakpad (optional 'm' after FUNC or PUBLIC)

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/tecken#924]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=1470092

**Comment by peterbe** [comment]
@luser 
I'll just make it work independent of the `m` being there.

**Comment by luser** [comment]
Sounds good. I could imagine people wanting that info at some point, like "is this a function that could be any one of a number of functions?" but I don't think that's super important to fix right now. I'd just like to not break symbolication when we update Breakpad in Firefox.
